version: "3.8"
services:
  postgres:
    image: postgres:16.8
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres_db
    ports:
      - "5432:5432"