spring:
  application:
    name: toListService

  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jackson:
    time-zone: Europe/Moscow
    serialization:
      write-dates-as-timestamps: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html      # URL для Swagger UI
    operationsSorter: method    # Сортировка операций по HTTP-методу
    tagsSorter: alpha           # Сортировка тегов по алфавиту

  api-docs:
      path: /v3/api-docs          # Путь к OpenAPI JSON
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  override-with-generic-response: true
  use-fqn-for-spring-controller: false


logging:
  pattern:
    console: "%d %-5level %logger-{15} : %msg%n"
    file: "%d %-5level %logger-{15} : %msg%n"
  level:
    root: info
    org:
      springframework:
        web: trace
  file:
    name: ${catalina.base:.}/logs/toList.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30